simple/urls.py
from django.urls import path
from simple import views

app_name = 'simple'

urlpatterns = [
    path('', views.index , name = 'index'),
    path('home/', views.Home.as_view() , name = 'home'),
    path('about_us/', views.about_us , name = 'about'),
    path('registration/', views.registration , name = 'registration'),
    path('login/', views.sign_in , name = 'login'),
    path('logout/', views.sign_out , name = 'logout'),
    path('gallery/', views.GalleryList.as_view() , name = 'lists'),
    path('create/', views.GalleryCreate.as_view() , name = 'create'),
    path('update/<pk>/', views.GalleryUpdate.as_view() , name = 'update'),
    path('delete/<pk>/', views.GalleryDelete.as_view() , name = 'delete'),

]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('simple.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simple/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.


class Registration(models.Model):
    choice = (('M','Male'),('F','Female'))
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length = 40, choices = choice , default = 'Male')
    DateOfBirth = models.DateTimeField(blank = True, null = True)
    def __str__(self):
        return self.user.username




class Gallery(models.Model):
    owner = models.CharField(max_length = 50, )
    images = models.ImageField(upload_to = 'picture/' , blank = False)
    description = RichTextField()

    def __str__(self):
        return self.owner

    def get_absolute_url(self):
        return reverse('simple:lists')

simple/forms.py
from django import forms
from django.contrib.auth.models import User
from simple.models import Registration


class RegistrationForm(forms.ModelForm):
    class Meta():
        model = Registration
        fields = ('age','gender')

class BaseUserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')

simple/views.py
# Imported modules and libary used for the views

from django.shortcuts import render,redirect
from simple.forms import BaseUserForm,RegistrationForm
from simple.models import Registration,Gallery
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse,reverse_lazy
from django.http import HttpResponse
from django.views.generic import (ListView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def index(request):
    return render(request,'simple/index.html',{})

# About us view (function)
def about_us(request):
    return render(request,'simple/about.html',{})

#  Home view for everyone that visit the website (function/class)
class Home(ListView):
    model = Gallery
    template_name = 'simple/home.html'
    context_object_name = 'lists'

#  Registration view for everyone that visit the website (function)
def registration(request):
    registered = False

    if request.method == 'POST':
        baseuser = BaseUserForm(request.POST)
        register = RegistrationForm(request.POST)

        if baseuser.is_valid() and register.is_valid():
            user = baseuser.save(commit = False)
            user.set_password(user.password)
            user.save()


            profile = register.save(commit = False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(baseuser.errors,register.errors)

    else:
        baseuser = BaseUserForm()
        register = RegistrationForm()
    return render(request, 'simple/registration.html', {
    'registered':registered,
    'baseuser':baseuser,
    'register':register
    })

#  Sign view for everyone that visit the website (function)
def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect('simple:lists')
            else:
                return HttpResponse('Account not Active ! ')
        else:
            return HttpResponse(f'Invalid Login Parameters, Either {username} or {password} is not correct !')
    else:
        return render(request,'simple/login.html',{})


#  Signout view for everyone that visit the website this required sign in first(function)
@login_required
def sign_out(request):
    logout(request)
    return redirect('simple:login')

#  GalleryList view for everyone that visit the website this required sign in first(function)
class GalleryList(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'simple/lists.html'
    model = Gallery
    template_name = 'simple/gallery.html'
    context_object_name = 'lists'

#  GalleryCreate view for everyone that visit the website the required sign in first(function/class), it allows to create new images
class GalleryCreate(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'simple/lists.html'
    model = Gallery
    template_name = 'simple/gallerycreate.html'
    fields = '__all__'

#  GalleryCreate view for everyone that visit the website the required sign in first(function/class), it allows to delete images

class GalleryDelete(LoginRequiredMixin,DeleteView):
    login_url = '/login/'
    redirect_field_name = 'simple/lists.html'
    model = Gallery
    template_name= 'simple/gallerydelete.html'
    fields = '__all__'

    success_url = reverse_lazy('simple:lists')

#  GalleryCreate view for everyone that visit the website the required sign in first(function/class), it allows to edit existing images
class GalleryUpdate(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'simple/lists.html'
    model = Gallery
    template_name = 'simple/gallerycreate.html'
    fields = ('images','description')

templates/simple/about.html
{% extends 'simple/base.html' %}

{% block content %}
<h5> Read <a href="https://www.linkedin.com/in/monsurulawal" target="_blank">about us </a> here....</h5>

{% endblock %}

templates/simple/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap_css/css/styletwos.css' %}">
    <script src="{% static 'bootstrap_css/js/jquery.js' %}" charset="utf-8"></script>
    <script src="{% static 'bootstrap_css/js/mini.js' %}" charset="utf-8"></script>
    <script src="{% static 'bootstrap_css/js/popper.js' %}" charset="utf-8"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="{% url 'simple:index' %}"><h2 class="navcolor">SCHOLAR NURTURE</h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active navcolor">
        <a class="nav-link" href="{% url 'simple:home' %}"><h4 class="navcolor">Home</h4><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'simple:about' %}"> <h4 class="navcolor">About US</h4></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'simple:lists' %}"><h4 class="navcolor">Galleries</h4></a>
      </li>
      {% endif %}
    </ul>
      <span>
        <ul>
          {% if user.is_authenticated %}
          <li class="list"><h4><a class="navcolor" href="{% url 'simple:logout' %}">Logout</a></h4></li>
          {% else %}
          <li class="list"><h4><a class="navcolor" href="{% url 'simple:login' %}">Login</a></h4></li>
          {% endif %}
        </ul>
      </span>
  </div>
</nav>

      <div class="container">
        {% block content %}

        {% endblock %}
      </div>

  </body>
</html>

templates/simple/gallery.html
{% extends 'simple/base.html' %}
{% load static %}
{% block content %}

<div class="jumbo_spacing">

</div>


<div class="row row-cols-1 row-cols-md-5">
  {% for list in lists %}
<div class="col mb-4">
  <div class="card">
    <img src="{{list.images.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{list.owner}}</h5>
      <p class="card-text">{{list.description|safe}}.</p>
      <a class="btn btn-primary"href="{% url 'simple:update' pk=list.pk %}">Edit</a>
      <a class="btn btn-primary"href="{% url 'simple:delete' pk=list.pk %}">Delete</a>
    </div>
  </div>
</div>
{% empty %}
<h1>No Information yet!</h1>
{% endfor %}
</div>


<a class="btn btn-primary"href="{% url 'simple:create' %}">Add Image</a>


{% endblock %}

templates/simple/gallerycreate.html
{% extends 'simple/base.html' %}

{% block content %}

<center>
  <h3>Add to Gallery</h3>
</center>
<div class="jumbotron jumbo_spacing">
  <center>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      {{form.media}}

      <input class="btn btn-primary"type="submit" name="" value="Add">
    </form>

  </center>

</div>
{% endblock %}

templates/simple/gallerydelete.html
{% extends 'simple/base.html' %}

{% block content %}


<div class="jumbo_spacing">
  <center>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
    <h3>Are you sure you want to delete {{object}}?</h3>
      <input class="btn btn-primary"type="submit" name="" value="Yes">
      <a class="btn btn-primary" href="{% url 'simple:lists' %}">No</a>
    </form>

  </center>

</div>
{% endblock %}

templates/simple/home.html
{% extends 'simple/base.html' %}
{% load static %}
{% block content %}

<div class="jumbo_spacing">

</div>

<div class="row row-cols-1 row-cols-md-3">
      {% for list in lists %}
      <div class="col mb-4">
        <div class="card">
          <img src="" alt="">

          <img src="{{list.images.url}}" class="card-img-top" alt="...">
          <div class="card-body">
           <h5 class="card-title">{{list.owner}}</h5>
            <p class="card-text">{{list.description|safe}}.</p>

          </div>
        </div>
      </div>
      {% empty %}
      <h1>No Information yet!</h1>
      {% endfor %}
    </div>
    <center>
      <h3><a href="{% url 'simple:registration' %}">Register</a> or <a  href="{% url 'simple:login' %}">Login</a></h3>

    </center>




{% endblock %}

templates/simple/index.html
{% extends 'simple/base.html' %}

{% block content %}
    <div class="jumbotron jumbo_spacing">
      <center>
          <h2 class="index_color">WELCOME TO MY MINI IMAGE KEEPER APP</h2>
          <p></p>
          <h5 class="index_color">WE ARE HAPPY TO HAVE YOU.</h5>
            <br/><br/>
            <h6>Click  <a  href="{% url 'simple:registration' %}">here to Register</a> to enjoy all the functionalities of the website!</h6>

      </center>
    </div>
    <center> <h6>&copy;Copyright 2021 </h6></center>
{% endblock %}

templates/simple/login.html
{% extends 'simple/base.html' %}

{% block content %}
<center><h2 class="login">Login</h2></center>
<div class="jumbotron jumbo_spacing">
  <center>

  <form  method="POST">
      {% csrf_token %}
      <label for="Username">Username :</label>
      <input type="text" name="username" value="Username">
      <p></p>
      <label for="Password">Password :</label>
      <input type="password" name="password" value="Password">
      <p></p>
      <input class="btn btn-primary" type="submit" name="" value="Login">
  </form>
  </center>
</div>


{% endblock %}

templates/simple/registration.html
{% extends 'simple/base.html' %}

{% block content %}
<center><h2 class="page">REGISTRATION PAGE</h2></center>

    <div class="jumbotron jumbo_spacing">
      {% if registered %}
      <center>
        <h2>You have successfully registered</h2>

        <h5>You can proceed to <a href="{% url 'simple:login' %}">login</a> now</h5>
      </center>
      {% else %}
          <form  method="POST">
            {% csrf_token %}
            {% for formone in baseuser %}

              <table>
                <tr>
                  <td class="labelcolor">{{formone.label}} : </td>
                  <td class="label">{{formone}}</td>
                </tr>

            {% endfor %}
            {% for formtwo in register %}
            <tr>
              <td class="labelcolor">{{formtwo.label}} :  </td>
              <td class="label">{{formtwo}}</td>

            </tr>
            {% endfor %}
              </table>
                <input class="btn btn-primary submit", type="submit" name="" value="Register">
            </form>
            {% endif %}


    </div>
{% endblock %}